### ISSUE TITLE
Problems in Stack to Image5D

### ISSUE THREAD

**Issue by RodenLuo** [fiji/Image_5D#2]
With this sample (A sample 5D data set is [available](http://imagej.net/images/Spindly-GFP.zip)) in Image5D [page](http://imagej.net/Image5D), I was not able to successfully perform Stack to Image5D. 

Repeat by:
1. Use Fiji ImageJ 2.0.0-rc-54/1.51g/Java 1.8.0_66 (64bit) on Win10 Enterprise.
2. Drop `mitosis.tif` into Fiji.
3. Click Plugins, Image5D, Stack to Image5D.
4. Leave everything as default, click OK.

The second channel is not converted correctly. As you can see below, all pixels in the second channel are shown as a very high value. 
![image](https://cloud.githubusercontent.com/assets/8460424/21464631/9cdc2c76-c937-11e6-9a9f-da64e1208867.png)

The same when I used Open Series As Image5D. But [MyoblastCells.tif](http://imagej.net/macros/images/MyoblastCells.zip) worked perfectly. Also tested on Mac OS X 10.10. The same problem.

Any help would be much appreciated!

**Comment by ctrueden** [comment]
Thanks for the bug report. Unfortunately, my time to address bugs like this is extremely limited these days, so I cannot promise when I will be able to investigate and fix it.

Is there some reason that ImageJ's built-in hyperstacks features do not work for you?

**Comment by RodenLuo** [comment]
Hi Curtis,
Thanks for your reply! I'm new to Fiji. I actually was looking for a specific viewer (see [post ](http://forum.imagej.net/t/stack-zoom-in-viewer-needed/3564)on ImageJ Forum). So I played with a bunch of visualization tools. Then the phenomenon above puzzled me at first, which I thought may be a bug.

After I realize there is an "Image>Color>Channels tool", I find they are similar. Hyperstack may even have more functionalities. I will explore it more and may use it to build the viewer I need. Thanks!

**Comment by RodenLuo** [comment]
Since most functions have been realized in the built-in viewer. Is it appropriate to add a similar notice in this [page](http://imagej.net/Cell_Counter) to Image5D's [page](http://imagej.net/Image5D)?

**Comment by ctrueden** [comment]
@RodenLuo Good idea. I added such a notice. As always with things on the website, please feel free to edit if you see ways to improve the wording etc.

**Comment by RodenLuo** [comment]
Good. Didn't notice we may able to edit it before. Will try for the next one if I find. Thanks.

**Comment by ctrueden** [comment]
@RodenLuo Sure! You just need to [create an account](http://imagej.net/Special:CreateAccount). In general, see the [Contributing](http://imagej.net/Contributing) page.
