### ISSUE TITLE
function/extension to get active channels and labels

### ISSUE THREAD

**Issue by pdd2110** [fiji/Image_5D#3]
Howdy,

Is there an IJ function or I5D extension to _get_ the active/displayed channels in the overlay, similar to `Stack.getActiveChannels` for a hyperstack?

Along the same lines, is there a way to _get_ the channel labels? `getInfo("slice.label")` returns a blank string.

Essentially I'm looking for _get_ compliments to the I5D `run("Set Channel Labels")` and `run("Set Channel Display")` commands.

Thanks,
P

**Comment by rasband** [comment]
An overlay is just a list of ROIs so there are no channels in an overlay.

Each image in a stack or hyperstack can have a slice label so one thing you can do is assign a channel label to the first C images in the stack, where C is the number of channels. Here is an example macro that does this:

```
  run("Organ of Corti (4D stack)");
  Stack.getDimensions(width, height, channels, slices, frames);
  for (c=1; c<=channels; c++)
     Property.setSliceLabel("Channel "+c, c);
  for (c=1; c<=channels; c++)
     print("label="+Property.getSliceLabel(c));

```

And this is the output:

```
  label=Channel 1
  label=Channel 2
  label=Channel 3
  label=Channel 4
```
